package model;
// Generated Apr 18, 2017 9:31:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mobil generated by hbm2java
 */
public class Mobil  implements java.io.Serializable {


     private String noKendaraan;
     private User user;
     private Set<Transaksi> transaksis = new HashSet<Transaksi>(0);

    public Mobil() {
    }

	
    public Mobil(String noKendaraan, User user) {
        this.noKendaraan = noKendaraan;
        this.user = user;
    }
    public Mobil(String noKendaraan, User user, Set<Transaksi> transaksis) {
       this.noKendaraan = noKendaraan;
       this.user = user;
       this.transaksis = transaksis;
    }
   
    public String getNoKendaraan() {
        return this.noKendaraan;
    }
    
    public void setNoKendaraan(String noKendaraan) {
        this.noKendaraan = noKendaraan;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set<Transaksi> getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set<Transaksi> transaksis) {
        this.transaksis = transaksis;
    }




}


