package model;
// Generated Apr 18, 2017 9:31:10 AM by Hibernate Tools 4.3.1



/**
 * Retailer generated by hbm2java
 */
public class Retailer  implements java.io.Serializable {


     private Integer id;
     private String companyName;

    public Retailer() {
    }

    public Retailer(String companyName) {
       this.companyName = companyName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }




}


