package model;
// Generated Apr 20, 2017 10:34:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transaksi generated by hbm2java
 */
public class Transaksi  implements java.io.Serializable {


     private Date date;
     private String rfid;
     private String statusTransaksi;
     private String keterangan;

    public Transaksi() {
    }

    public Transaksi(Date date, String rfid, String statusTransaksi, String keterangan) {
       this.date = date;
       this.rfid = rfid;
       this.statusTransaksi = statusTransaksi;
       this.keterangan = keterangan;
    }
   
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getRfid() {
        return this.rfid;
    }
    
    public void setRfid(String rfid) {
        this.rfid = rfid;
    }
    public String getStatusTransaksi() {
        return this.statusTransaksi;
    }
    
    public void setStatusTransaksi(String statusTransaksi) {
        this.statusTransaksi = statusTransaksi;
    }
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }




}


