package model;
// Generated Apr 17, 2017 6:33:02 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transaksi generated by hbm2java
 */
public class Transaksi  implements java.io.Serializable {


     private Date date;
     private Mobil mobil;
     private String noParkir;
     private int bill;
     private Date startTime;
     private Date endTime;
     private String statusTrasaksi;

    public Transaksi() {
    }

    public Transaksi(Date date, Mobil mobil, String noParkir, int bill, Date startTime, Date endTime, String statusTrasaksi) {
       this.date = date;
       this.mobil = mobil;
       this.noParkir = noParkir;
       this.bill = bill;
       this.startTime = startTime;
       this.endTime = endTime;
       this.statusTrasaksi = statusTrasaksi;
    }
   
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Mobil getMobil() {
        return this.mobil;
    }
    
    public void setMobil(Mobil mobil) {
        this.mobil = mobil;
    }
    public String getNoParkir() {
        return this.noParkir;
    }
    
    public void setNoParkir(String noParkir) {
        this.noParkir = noParkir;
    }
    public int getBill() {
        return this.bill;
    }
    
    public void setBill(int bill) {
        this.bill = bill;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public String getStatusTrasaksi() {
        return this.statusTrasaksi;
    }
    
    public void setStatusTrasaksi(String statusTrasaksi) {
        this.statusTrasaksi = statusTrasaksi;
    }




}


